module.exports = {
	plugins: [require('prettier-plugin-tailwindcss')],
	printWidth: 80,
	tabWidth: 2,
	useTabs: true,
	semi: false,
	singleQuote: true,
	quoteProps: 'as-needed',
	jsxSingleQuote: false,
	trailingComma: 'all',
	requirePragma: false,
	insertPragma: false,
	htmlWhitespaceSensitivity: 'css',
	endOfLine: 'lf',
}
