module.exports = {
	plugins: [require('prettier-plugin-tailwindcss')],
	arrowParens: 'always',
	bracketSameLine: false,
	bracketSpacing: true,
	semi: false,
	singleQuote: true,
	jsxSingleQuote: true,
	quoteProps: 'as-needed',
	trailingComma: 'all',
	htmlWhitespaceSensitivity: 'css',
	proseWrap: 'preserve',
	insertPragma: false,
	printWidth: 80,
	requirePragma: false,
	tabWidth: 2,
	useTabs: true,
	embeddedLanguageFormatting: 'auto',
}
