image: oven/bun:latest

stages:
  - test

variables:
  # Enable CI mode
  CI: "true"

# Cache dependencies
cache:
  key:
    files:
      - bun.lock
  paths:
    - node_modules/

unit-tests:
  stage: test
  script:
    - bun install --frozen-lockfile
    - bun run test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 30 days

e2e-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.57.0-jammy
  before_script:
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
  script:
    - bun install --frozen-lockfile
    - bun run test:e2e:ci
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 7 days
